
test:
	nosetests -v

debug:
	nosetests --debug=ion,iondb,tests -v -d -s test_plugin_loader.py
	nosetests --debug=ion,iondb,tests -v -d -s test_plugins.py
	nosetests --debug=ion,iondb,tests -v -d -s test_plugin_framework.py

