#!/bin/bash
# Copyright (C) 2011 Ion Torrent Systems, Inc. All Rights Reserved

function print_help()
{
	echo
	echo "Usage: publish [--dev|--alpha|--patch] filename"
    echo
    echo "Default location to publish to is lucid-alpha"
    echo -e "--lucid-dev\tlucid-dev"
    echo -e "--lucid-alpha\tlucid-alpha"
    echo -e "--lucid-proton-alpha\tlucid-proton-alpha"
    echo -e "--patchtest\tpatchtest"
    echo
}

#---    First, if no args given, print help ---#
if [ $# == 0 ]; then
    print_help
    exit 0
fi

# last argument is file to transfer
for arg in $*; do
	PKGFILE=$arg
done

# Flag control Packages.gz file creation
UPDATE_PKGFILE=1

#---    We convert all arguments to lower case  ---#
while [ $# != 0 ]; do
    case ${1,,} in
    '--lucid-dev')
    	PUBDIR="lucid-dev"
    ;;
    '--lucid-alpha')
    	PUBDIR="lucid-alpha"
    ;;
    '--lucid-proton-alpha')
    	PUBDIR="lucid-proton-alpha"
    ;;
    '--patchtest')
    	PUBDIR="patchtest"
    ;;
    '--no-pkgfile')
        UPDATE_PKGFILE=0
    ;;
    esac
    shift
done

USER=root
SERVER=friartuck.ite
PUBDIR=${PUBDIR-"lucid-alpha"}
PUBPATH=/home/aptadmin/public_html/updates_server_root/updates/software/$PUBDIR

if [ ! -f "$PKGFILE" ]; then
   echo "ERROR: $PKGFILE not found."
   exit 1
fi

#prevent accidental overwriting of existing file
fname=$(basename $PKGFILE)
file=$(\
ssh $USER@$SERVER ls $PUBPATH/$fname 2>/dev/null
)
if [ "$file" == "$PUBPATH/$fname" ]; then
   echo "ERROR: File exists: $file"
   exit 1
fi

echo "Copying $PKGFILE to $PUBDIR"
scp -p $PKGFILE $USER@$SERVER:$PUBPATH
fname=$(basename $PKGFILE)
file=$(\
ssh $USER@$SERVER ls $PUBPATH/$fname
)
if [ "$file" == "" ]; then
   echo "ERROR: There was an error copying $fname"
   exit 1
fi

if [ $UPDATE_PKGFILE == 1 ]; then
    # Create the file in a temporary location, then move it to its final location.  This will minimize the downtime
    # to accessing the apt repository.  We used to remove the file, then rewrite it - a process that can take several
    # minutes.
    echo "Writing new Packages.gz file"
    pkgfile=$(mktemp)
    ssh $USER@$SERVER "cd $PUBPATH/.. && apt-ftparchive packages $PUBDIR | gzip > $pkgfile && mv $pkgfile $PUBDIR/Packages.gz"
    if [ $? -ne 0 ]
    then
        echo "There was an error creating the Packages.gz file"
        exit 1
    fi
fi
exit 0
