---
# file: roles/common/handlers/main.yml

- name: update grub
  command: /usr/sbin/update-grub
  when: not docker_image

- name: update initramfs
  command: /usr/sbin/update-initramfs -u
  when: not docker_image
