#!/bin/bash
# Copyright (C) 2010 Ion Torrent Systems, Inc. All Rights Reserved
set -e
#set -x
#echo "postrm $@"
case "$1" in
	abort-install)
		rm -rf @ION_GPU_PREFIX@/devdriver
        rm -rf /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
        if [ -e /etc/rc.local ]; then
		    sed -i "/create_nvidia_files/d" /etc/rc.local
	    fi
    ;;
esac

exit 0

