#!/bin/bash
# Copyright (C) 2010 Ion Torrent Systems, Inc. All Rights Reserved
set -e
#set -x
#echo "prerm $@"
# Notes:
# To delete NVIDIA drivers, ???
# To delete cuda toolkit, delete directory /usr/local/cuda

case "$1" in
	remove)
        # only if drivers were installed do we uninstall them
        if [ -d @ION_GPU_PREFIX@/devdriver ]; then
            cd @ION_GPU_PREFIX@/devdriver
            ./nvidia-installer --uninstall --ui=none --no-questions
            cd - >/dev/null
        fi
    	rm -rf @ION_GPU_PREFIX@/devdriver
        rm -rf /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
        if [ -e /etc/rc.local ]; then 
            sed -i "/create_nvidia_files/d" /etc/rc.local
	    fi
    ;;
    upgrade)
        # only if drivers were installed do we uninstall them
        if [ -d @ION_GPU_PREFIX@/devdriver ]; then
            cd @ION_GPU_PREFIX@/devdriver
            ./nvidia-installer --uninstall --ui=none --no-questions
            cd - >/dev/null
        fi
    ;;
esac

exit 0
