#!/bin/bash
# Copyright (C) 2012 Ion Torrent Systems, Inc. All Rights Reserved
set -x
#echo $0 $1 $2
### BEGIN INIT INFO
# Provides:          oia
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop oia daemon
### END INIT INFO

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

DAEMON='/software/oia/oiad.py'
DAEMON_NAME='oia'
USERID='root'
PIDFILE="/var/run/${DAEMON_NAME}.pid"

function start_function ()
{
    # Start the Job Server
    if [ -f ${DAEMON} ]
    then
        start-stop-daemon \
            --start \
            --chuid ${USERID} \
            --user ${USERID} \
            --pidfile ${PIDFILE} \
            --make-pidfile \
            --background \
            --startas $DAEMON

        if [ $? -eq 0 ]
        then
            pid=`cat ${PIDFILE}`
            echo "Starting $DAEMON_NAME pid = $pid"
        else
            echo "Failed to start: $DAEMON_NAME"
            return 1
        fi
    else
        echo "Can't find $DAEMON_NAME. Broken install of Torrent Server?"
        return 1
    fi
}

function stop_function ()
{
    echo "Stopping $DAEMON_NAME"
    start-stop-daemon \
        --stop \
        --user ${USERID} \
        --pidfile ${PIDFILE} \
        --retry 5
    rm -f ${PIDFILE}
}

function status ()
{
    if [ -f ${PIDFILE} ]; then
        status_of_proc -p $PIDFILE $DAEMON $DAEMON_NAME && exit 0 || exit $?
    else
        echo "No pid file: ${PIDFILE}"
        return 1
    fi
}

case $1 in
	start)
		start_function
	;;
	stop)
		stop_function
	;;
	restart)
		stop_function
		start_function
	;;
	status)
		status
	;;
    *)
    echo " * Usage: /etc/init.d/${DAEMON_NAME} {start|stop|status|restart}"
esac
