/* Copyright (C) 2012 Ion Torrent Systems, Inc. All Rights Reserved */

#include <cassert>
#include <Rcpp.h>
#include "hdf5.h"

using namespace std;

// Read in H5 file generated by FlowErrTest, and return contents to R.

RcppExport SEXP LoadFlowErr(SEXP RFileName)
{
    // Open the H5 file, and get to the dataset:
    const char* fileName = Rcpp::as<const char*>(RFileName);

    hid_t file = H5Fopen(fileName, H5F_ACC_RDONLY, H5P_DEFAULT);
    assert(file >= 0);

    hid_t dset = H5Dopen(file, "/dset", H5P_DEFAULT);
    assert(dset >= 0);

    // Get dimensions for the data set:
    hid_t space = H5Dget_space(dset);
    assert(space >= 0);

    int ndims = H5Sget_simple_extent_ndims(space);
    assert(ndims == 3);

    hsize_t dims[ndims];
    hsize_t maxDims[ndims];
    int result = H5Sget_simple_extent_dims(space, dims, maxDims);
    assert(result != 0);
    if (result==0) {result=0;}; // soak up error message for never using result

    int numFlows  = dims[0];
    int maxReadHP = dims[1];
    int maxRefHP  = dims[2];

    // Read in the data set:
    int counts[numFlows][maxReadHP][maxRefHP];
    size_t nelem  = numFlows * maxReadHP * maxRefHP;
    herr_t status = H5Dread(dset, H5T_NATIVE_INT, H5S_ALL, H5S_ALL, H5P_DEFAULT, counts);
    assert(status >= 0);

    // Change to R-style column-major order:
    int Rcounts[nelem];
    for(int i=0; i<numFlows; ++i){
        for(int j=0; j<maxReadHP; ++j){
            for(int k=0; k<maxRefHP; ++k){
                Rcounts[k*numFlows*maxReadHP + j*numFlows + i] = counts[i][j][k];
            }
        }
    }

    // Close file:
    status = H5Dclose(dset);
    assert(status >= 0);

    status = H5Fclose(file);
    assert(status >= 0);

    // Package results for return to R:
    RcppResultSet rs;
    rs.add("numFlows",  numFlows);
    rs.add("maxReadHP", maxReadHP);
    rs.add("maxRefHP",  maxRefHP);
    rs.add("counts",    Rcounts, nelem);

    return rs.getReturnList();
}

