#!/bin/bash
# Copyright (C) 2014 Life Technologies Inc. All Rights Reserved
#
# NOTE: The only output to stdout should be the versions that are available for install
#
LATEST=5.4.0
VER_AVAIL=( 4.6 5.0.5 5.2.2 $LATEST )

echo ${VER_AVAIL[@]}
