#!/bin/bash
#
#	Clear test data from server
#
set -e
source ./ts_functions
needs_root

#	Clean data from dbase
printf "Dropping iondb database\n"
dropdb -i -e iondb -U postgres
if [ $? -ne 0 ]; then
	echo "ERROR: Could not drop iondb"
	exit 1
fi

#	Clean test data from filesystem
printf "Deleting raw data and analysis results\n"
rm -ir /results/PGM_test
rm -ir /results/analysis/output/Home/*

exit 0
