#!/bin/bash
# Copyright (C) 2010 Ion Torrent Systems, Inc. All Rights Reserved
#
# Torrent Server Parameters
#

TSCONFIG_SRC_DIR='/usr/share/ion-tsconfig'
TSCONFIG_LOG_DIR='/var/log/ion'
TSCONFIG_INSTALL_LOG='tsconfig_install.log'
TSCONFIG_DEBUG_LOG='tsconfig_debug.log'
TSCONFIG_LOG_BASENAME='tsconf.log'
TSCONFIG_DIR='/etc/torrentserver'
TSCONFIG_CONF='tsconf.conf'
TSCONFIG_MINT_CONF_DIR='mint-config'
SGE_ROOT=/var/lib/gridengine/
SGE_CELL=iontorrent
TEXT_WARN_MSG=( "#\n",
"# WARNING\n",
"# This file has been configured and/or optimized for the Torrent Server.\n",
"# It is recommended that you do not alter or edit this file.\n",
"#\n",
"# Changing this file may break your Torrent Server immediately or problems\n",
"# may not surface till a later software update.  Resolution of problems\n",
"# will likely be delayed because of custom modifications to this file.\n"
)
TSCONFIG_ION_UPDATE_URL="http://ionupdates.com"
TSCONFIG_UBUNTU_UPDATE_URL="http://us.archive.ubuntu.com"
TSCONFIG_PACKAGELIST_FILE=${TSCONFIG_SRC_DIR}/torrentsuite-packagelist.json
TSCONFIG_CARD_ID="PERC H810"
TSCONFIG_CLUSTER_ADMIN=ionadmin # user with ssh-key on compute nodes for passwordless entry

# Source any local edits
if [ -r ${TSCONFIG_SRC_DIR}/ts_params.local ]; then
    source ${TSCONFIG_SRC_DIR}/ts_params.local
fi
# Ansible specific variables
ANSIBLE_HOME=$TSCONFIG_SRC_DIR/ansible
MY_HOSTS=torrentsuite_hosts
if [ -r $ANSIBLE_HOME/torrentsuite_hosts_local ]; then
    MY_HOSTS=torrentsuite_hosts_local
fi

# Flag file to enable apache2 maintenance page display
MAINTENANCE_WEB=/var/www/maintenance.enable

# system service restart script
CHECK_SYSTEM_SERVICES_PY='/opt/ion/iondb/bin/check_system_services.py'

# Get th major platform
TS_GET_PLATFORM_PY=${TSCONFIG_SRC_DIR}/TSgetPlatform.py
TS_SWITCH_REPO_PY=${TSCONFIG_SRC_DIR}/TSswitchRepo.py

META_DATA=($(python $TS_GET_PLATFORM_PY))
MAJOR_PLATFORM=${META_DATA[0]}
ENABLE_DEPRECATION=${META_DATA[1]}

PGM_REPO="pgm_or_proton_only"
S5_REPO="s5_only"
